#' Massive case_when function
#'
#' Placement nomenclatures occasionally fall apart. This gets around that. Clunky but it works
#'
#' @param tbl Dataframe of Sprinklr data that includes a column with the placement name
#'
#' @return Dataframe with separated placement names
#' @export
#'
#' @examples
#' \dontrun{
#' This gets used in tandem with appply_nomenclature()
#' }
massive_cw <- function(tbl){
  tbl |>
    dplyr::mutate(p_division_code = dplyr::case_when(stringr::str_detect(part1, '_ALL') ~ 'All',
                                              stringr::str_detect(part1, '_CEN') ~ 'Central',
                                              stringr::str_detect(part1, '_NED') ~ 'Northeast',
                                              stringr::str_detect(part1, '_FUS') ~ 'Full USA',
                                              stringr::str_detect(part1, '_WST') ~ 'West',
                                              TRUE ~ NA),
           p_region_code = dplyr::case_when(stringr::str_detect(part1, '_ALLR') ~ 'All',
                                            stringr::str_detect(part1, '_MULTR') ~ 'Mulltiple',
                                            stringr::str_detect(part1, '_FLU') ~ 'Full USA',
                                            stringr::str_detect(part1, '_BS') ~ 'Big South',
                                            stringr::str_detect(part1, '_FLR') ~ 'Florida',
                                            stringr::str_detect(part1, '_HL') ~ 'Heartland',
                                            stringr::str_detect(part1, '_GCR') ~ 'Greater Chicago',
                                            stringr::str_detect(part1, '_BLY') ~ 'Beltway',
                                            stringr::str_detect(part1, '_FRE') ~ 'Freedom',
                                            stringr::str_detect(part1, '_GBR') ~ 'Greater Boston',
                                            stringr::str_detect(part1, '_KEY') ~ 'Keystone',
                                            stringr::str_detect(part1, '_WNE') ~ 'Western New England',
                                            stringr::str_detect(part1, '_CA') ~ 'California',
                                            stringr::str_detect(part1, '_GTX') ~ 'Greater Texas',
                                            stringr::str_detect(part1, '_MTW') ~ 'Mountain West',
                                            stringr::str_detect(part1, '_PNW') ~ 'Pacific Northwest',
                                            stringr::str_detect(part1, '_MDW') ~ 'Midwest',
                                            TRUE ~ NA),
           p_dma_code = dplyr::case_when(stringr::str_detect(part1, '_ALLD') ~ 'All',
                                         stringr::str_detect(part1, '_MULTD') ~ 'Multiple',
                                         stringr::str_detect(part1, '_FUL') ~ 'Full USA',
                                         stringr::str_detect(part1, '_AST') ~ 'Albany-Schenectady-Troy',
                                         stringr::str_detect(part1, '_ALB') ~ 'Albuquerque-Santa Fe',
                                         stringr::str_detect(part1, '_AM') ~ 'Amarillo',
                                         stringr::str_detect(part1, '_ATL') ~ 'Atlanta',
                                         stringr::str_detect(part1, '_AUG') ~ 'Augusta',
                                         stringr::str_detect(part1, '_BAL') ~ 'Baltimore',
                                         stringr::str_detect(part1, '_BIR') ~ 'Birmingham \\(Ann and Tusc\\)',
                                         stringr::str_detect(part1, '_BLU') ~ 'Bluefield-Beckley-Oak Hill',
                                         stringr::str_detect(part1, '_BOS') ~ 'Boston',
                                         stringr::str_detect(part1, '_BG') ~ 'Bowling Green',
                                         stringr::str_detect(part1, '_BUF') ~ 'Buffalo',
                                         stringr::str_detect(part1, '_BUR') ~ 'Burlington-Plattsburgh',
                                         stringr::str_detect(part1, '_CSD') ~ 'Champaign&Sprngfld-Decatur',
                                         stringr::str_detect(part1, '_CHA') ~ 'Charleston, SC',
                                         stringr::str_detect(part1, '_CH') ~ 'Charleston-Huntington',
                                         stringr::str_detect(part1, '_CHV') ~ 'Charlottesville',
                                         stringr::str_detect(part1, '_CHAT') ~ 'Chattanooga',
                                         stringr::str_detect(part1, '_CHI') ~ 'Chicago',
                                         stringr::str_detect(part1, '_CC') ~ 'Chico-Redding',
                                         stringr::str_detect(part1, '_CIN') ~ 'Cincinnati',
                                         stringr::str_detect(part1, '_CLA') ~ 'Clarksburg-Weston',
                                         stringr::str_detect(part1, '_CSP') ~ 'Colorado Springs-Pueblo',
                                         stringr::str_detect(part1, '_COL') ~ 'Columbia, SC',
                                         stringr::str_detect(part1, '_COO') ~ 'Columbus, GA \\(Opelika, AL\\)',
                                         stringr::str_detect(part1, '_CTW') ~ 'Columbus-Tupelo-W Pnt-Hstn',
                                         stringr::str_detect(part1, '_DAV') ~ 'Davenport-R.Island-Moline',
                                         stringr::str_detect(part1, '_DAY') ~ 'Dayton',
                                         stringr::str_detect(part1, '_DEN') ~ 'Denver',
                                         stringr::str_detect(part1, '_DET') ~ 'Detroit',
                                         stringr::str_detect(part1, '_DOT') ~ 'Dothan',
                                         stringr::str_detect(part1, '_EP') ~ 'El Paso \\(Las Cruces\\)',
                                         stringr::str_detect(part1, '_EUG') ~ 'Eugene',
                                         stringr::str_detect(part1, '_EVA') ~ 'Evansville',
                                         stringr::str_detect(part1, '_FLI') ~ 'Flint-Saginaw-Bay City',
                                         stringr::str_detect(part1, '_FRV') ~ 'Fresno-Visalia',
                                         stringr::str_detect(part1, '_FMN') ~ 'Ft. Myers-Naples',
                                         stringr::str_detect(part1, '_FW') ~ 'Ft. Wayne',
                                         stringr::str_detect(part1, '_GAI') ~ 'Gainesville',
                                         stringr::str_detect(part1, '_GR') ~ 'Grand Rapids-Kalmzoo-B.Crk',
                                         stringr::str_detect(part1, '_GB') ~ 'Green Bay-Appleton',
                                         stringr::str_detect(part1, '_GHW') ~ 'Greensboro-H.Point-W.Salem',
                                         stringr::str_detect(part1, '_GSA') ~ 'Greenvll-Spart-Ashevll-And',
                                         stringr::str_detect(part1, '_HLL') ~ 'Harrisburg-Lncstr-Leb-York',
                                         stringr::str_detect(part1, '_HAR') ~ 'Harrisonburg',
                                         stringr::str_detect(part1, '_HNH') ~ 'Hartford & New Haven',
                                         stringr::str_detect(part1, '_HLL') ~ 'Hattiesburg-Laurel',
                                         stringr::str_detect(part1, '_HOU') ~ 'Houston',
                                         stringr::str_detect(part1, '_HUD') ~ 'Huntsville-Decatur \\(Flor\\)',
                                         stringr::str_detect(part1, '_IND') ~ 'Indianapolis',
                                         stringr::str_detect(part1, '_JAM') ~ 'Jackson, MS',
                                         stringr::str_detect(part1, '_JAT') ~ 'Jackson, TN',
                                         stringr::str_detect(part1, '_JAC') ~ 'Jacksonville',
                                         stringr::str_detect(part1, '_JAS') ~ 'Johnstown-Altoona-St Colge',
                                         stringr::str_detect(part1, '_KC') ~ 'Kansas City',
                                         stringr::str_detect(part1, '_KNO') ~ 'Knoxville',
                                         stringr::str_detect(part1, '_LAF') ~ 'Lafayette, IN',
                                         stringr::str_detect(part1, '_LAN') ~ 'Lansing',
                                         stringr::str_detect(part1, '_LR') ~ 'Little Rock-Pine Bluff',
                                         stringr::str_detect(part1, '_LOU') ~ 'Louisville',
                                         stringr::str_detect(part1, '_MAC') ~ 'Macon',
                                         stringr::str_detect(part1, '_MAN') ~ 'Mankato',
                                         stringr::str_detect(part1, '_MEM') ~ 'Memphis',
                                         stringr::str_detect(part1, '_MER') ~ 'Meridan',
                                         stringr::str_detect(part1, '_MIA') ~ 'Miami-Ft. Lauderdale',
                                         stringr::str_detect(part1, '_MIN') ~ 'Minneapolis-St. Paul',
                                         stringr::str_detect(part1, '_MOB') ~ 'Mobile-Pensacola \\(Ft Walt\\)',
                                         stringr::str_detect(part1, '_MED') ~ 'Monroe-El Dorado',
                                         stringr::str_detect(part1, '_MON') ~ 'Monterey-Salinas',
                                         stringr::str_detect(part1, '_NAS') ~ 'Nashville',
                                         stringr::str_detect(part1, '_NO') ~ 'New Orleans',
                                         stringr::str_detect(part1, '_NY') ~ 'New York',
                                         stringr::str_detect(part1, '_NPN') ~ 'Norfolk-Portsmth-Newpt Nws',
                                         stringr::str_detect(part1, '_ORL') ~ 'Orlando-Daytona Bch-Melbrn',
                                         stringr::str_detect(part1, '_PAD') ~ 'Paducah-Cape Girard-Harsbg',
                                         stringr::str_detect(part1, '_PC') ~ 'Panama City',
                                         stringr::str_detect(part1, '_PEO') ~ 'Peoria-Bloomington',
                                         stringr::str_detect(part1, '_PHI') ~ 'Philadelphia',
                                         stringr::str_detect(part1, '_PHO') ~ 'Phoenix \\(Prescott\\)',
                                         stringr::str_detect(part1, '_PIT') ~ 'Pittsburgh',
                                         stringr::str_detect(part1, '_POR') ~ 'Portland, OR',
                                         stringr::str_detect(part1, '_PA') ~ 'Portland-Auburn',
                                         stringr::str_detect(part1, '_PRO') ~ 'Providence-New Bedford',
                                         stringr::str_detect(part1, '_QUI') ~ 'Quincy-Hannibal-Keokuk',
                                         stringr::str_detect(part1, '_RAL') ~ 'Raleigh-Durham \\(Fayetvlle\\)',
                                         stringr::str_detect(part1, '_RIC') ~ 'Richmond-Petersburg',
                                         stringr::str_detect(part1, '_ROA') ~ 'Roanoke-Lynchburg',
                                         stringr::str_detect(part1, '_ROC') ~ 'Rockford',
                                         stringr::str_detect(part1, '_SAC') ~ 'Sacramnto-Stkton-Modesto',
                                         stringr::str_detect(part1, '_SAL') ~ 'Salisbury',
                                         stringr::str_detect(part1, '_SLC') ~ 'Salt Lake City',
                                         stringr::str_detect(part1, '_SF') ~ 'San Francisco',
                                         stringr::str_detect(part1, '_SAN') ~ 'SantaBarbra-SanMar-SanLuOb',
                                         stringr::str_detect(part1, '_SAV') ~ 'Savannah',
                                         stringr::str_detect(part1, '_SEA') ~ 'Seattle-Tacoma',
                                         stringr::str_detect(part1, '_SHR') ~ 'Shreveport',
                                         stringr::str_detect(part1, '_SB') ~ 'South Bend-Elkhart',
                                         stringr::str_detect(part1, '_SPO') ~ 'Spokane',
                                         stringr::str_detect(part1, '_SPR') ~ 'Springfield-Holyoke',
                                         stringr::str_detect(part1, '_TAL') ~ 'Tallahassee-Thomasville',
                                         stringr::str_detect(part1, '_TAM') ~ 'Tampa-St. Pete',
                                         stringr::str_detect(part1, '_TH') ~ 'Terre Haute',
                                         stringr::str_detect(part1, '_TOL') ~ 'Toledo',
                                         stringr::str_detect(part1, '_TRIC') ~ 'Tri-Cities, TN-VA',
                                         stringr::str_detect(part1, '_TUC') ~ 'Tucson \\(Sierra Vista\\)',
                                         stringr::str_detect(part1, '_DC') ~ 'Washington, DC',
                                         stringr::str_detect(part1, '_WPB') ~ 'West Palm Beach-Ft. Pierce',
                                         stringr::str_detect(part1, '_WHE') ~ 'Wheeling-Steubenville',
                                         stringr::str_detect(part1, '_WB') ~ 'Wilkes Barre-Scranton',
                                         stringr::str_detect(part1, '_AAZ') ~ 'All USA  ALL ZIP',
                                         stringr::str_detect(part1, '_YOU') ~ 'Youngstown',
                                         TRUE ~ NA),
           p_zip_code = dplyr::case_when(stringr::str_detect(part1, '_ALLZ') ~ 'All',
                                         stringr::str_detect(part1, '_FIOS') ~ 'Fios Zip',
                                         stringr::str_detect(part1, '_NONFIOS') ~ 'Non Fios Zip',
                                         stringr::str_detect(part1, '_SATLLTE') ~ 'Satellite Zip',
                                         stringr::str_detect(part1, '_EPB') ~ 'EPB Zip',
                                         stringr::str_detect(part1, '_KNOLOG') ~ 'Knology Zip',
                                         stringr::str_detect(part1, '_UVERSE') ~ 'Uverse Zip',
                                         stringr::str_detect(part1, '_CL') ~ 'Century Link',
                                         stringr::str_detect(part1, '_LAN') ~ 'Uverse Zip',
                                         stringr::str_detect(part1, '_MDCT') ~ 'MDCT Zip',
                                         stringr::str_detect(part1, '_WOW') ~ 'WOW Zip',
                                         stringr::str_detect(part1, '_RCN') ~ 'RCN Zip',
                                         stringr::str_detect(part1, '_LHARP') ~ 'LaHarpe Zip',
                                         stringr::str_detect(part1, '_ITV3') ~ 'ITV3 Zip',
                                         stringr::str_detect(part1, '_FRO') ~ 'Frontier Fiber Zip',
                                         TRUE ~ NA),
           p_retargeting_segment = dplyr::case_when(stringr::str_detect(part1, '_NOSEG') ~ 'None',
                                                    stringr::str_detect(part1, '_HMPG') ~ 'Home Page Visitor',
                                                    stringr::str_detect(part1, '_PDPG') ~ 'Product/Plan Page Visitor',
                                                    stringr::str_detect(part1, '_SPPG') ~ 'Support Page Visitor',
                                                    stringr::str_detect(part1, '_SXPG') ~ 'Shop \\(Xfinity Mobile\\)',
                                                    stringr::str_detect(part1, '_PSLP') ~ 'Paid Search Visitor',
                                                    stringr::str_detect(part1, '_NCAR') ~ 'Nascar',
                                                    stringr::str_detect(part1, '_RETEN') ~ 'Retention',
                                                    stringr::str_detect(part1, '_COMP') ~ 'Competitive Visitor',
                                                    stringr::str_detect(part1, '_XHS') ~ 'Xfinity Home Visitor',
                                                    stringr::str_detect(part1, '_BFLW') ~ 'BuyFlow Visitor',
                                                    stringr::str_detect(part1, '_CUST') ~ 'Existing Customer',
                                                    stringr::str_detect(part1, '_MOVSB') ~ 'Movers Sub',
                                                    stringr::str_detect(part1, '_MOVER') ~ 'Mover',
                                                    stringr::str_detect(part1, '_CTOUT') ~ 'Clicks Out To Site',
                                                    stringr::str_detect(part1, '_DEALS') ~ 'Deals',
                                                    stringr::str_detect(part1, '_PRICE') ~ 'Pricing',
                                                    stringr::str_detect(part1, '_TOOL') ~ 'Tools',
                                                    stringr::str_detect(part1, '_DCOM') ~ 'DOTCOM',
                                                    stringr::str_detect(part1, '_LDPG') ~ 'Landing Page',
                                                    stringr::str_detect(part1, '_BIZO') ~ 'Bizo',
                                                    stringr::str_detect(part1, '_TARGUS') ~ 'TargusInfo',
                                                    stringr::str_detect(part1, '_BLUE') ~ 'BlueKai',
                                                    stringr::str_detect(part1, '_MVOOF') ~ 'Movers Out Of Footprint',
                                                    stringr::str_detect(part1, '_BFOOF') ~ 'Buyflow Out Of Footprint',
                                                    stringr::str_detect(part1, '_LCTN') ~ 'Location',
                                                    stringr::str_detect(part1, '_LOCL') ~ 'Local',
                                                    stringr::str_detect(part1, '_PPOOF') ~ 'Product Page Out Of Footprint',
                                                    stringr::str_detect(part1, '_ABNDMT') ~ 'Lead Gen Abandonment Visitor',
                                                    stringr::str_detect(part1, '_UPPERFNL') ~ 'Upper Funnel Message Visitor',
                                                    stringr::str_detect(part1, '_EXLT') ~ 'eXelate',
                                                    TRUE ~ NA),
           p_sub_vendor_name = dplyr::case_when(stringr::str_detect(part1, '_RKU') ~ 'Roku',
                                                stringr::str_detect(part1, '_HLU') ~ 'Hulu',
                                                stringr::str_detect(part1, '_SFY') ~ 'Spotify',
                                                stringr::str_detect(part1, '_PND') ~ 'Pandora',
                                                stringr::str_detect(part1, '_DAX') ~ 'DAX',
                                                stringr::str_detect(part1, '_YTT') ~ 'YouTube',
                                                stringr::str_detect(part1, '_PCK') ~ 'Peacock',
                                                stringr::str_detect(part1, '_NBC') ~ 'NBCU',
                                                stringr::str_detect(part1, '_META') ~ 'Meta',
                                                stringr::str_detect(part1, '_SNP') ~ 'Snapchat',
                                                stringr::str_detect(part1, '_TWX') ~ 'Twitter/X',
                                                stringr::str_detect(part1, '_DSY') ~ 'Disney',
                                                stringr::str_detect(part1, '_TKK') ~ 'TikTok',
                                                stringr::str_detect(part1, '_PRT') ~ 'Paramount',
                                                stringr::str_detect(part1, '_SME') ~ 'Same as Vendor',
                                                TRUE ~ NA),
           p_platform = dplyr::case_when(stringr::str_detect(part1, '_DT') ~ 'Desktop',
                                         stringr::str_detect(part1, '_MO') ~ 'Mobile',
                                         stringr::str_detect(part1, '_DM') ~ 'Desktop and Mobile',
                                         stringr::str_detect(part1, '_CHD') ~ 'Connected Home Devices',
                                         stringr::str_detect(part1, '_CTV') ~ 'CTV',
                                         stringr::str_detect(part1, '_GAME') ~ 'Gaming',
                                         stringr::str_detect(part1, '_HOOH') ~ 'Out of Home',
                                         stringr::str_detect(part1, '_TAB') ~ 'Tablet',
                                         stringr::str_detect(part1, '_CROSS') ~ 'Cross Screen',
                                         TRUE ~ NA),
           p_placement_execution_type = dplyr::case_when(stringr::str_detect(part1, '_BAN') ~ 'BANNER',
                                                         stringr::str_detect(part1, '_TKO') ~ 'TAKEOVER',
                                                         stringr::str_detect(part1, '_LOG') ~ 'LOGO',
                                                         stringr::str_detect(part1, '_NAT') ~ 'NATIVE UNIT',
                                                         stringr::str_detect(part1, '_RMBAN') ~ 'High Impact Banner',
                                                         stringr::str_detect(part1, '_RMTKO') ~ 'High Impact Takeover',
                                                         stringr::str_detect(part1, '_HOLV') ~ 'High Impact OLV',
                                                         stringr::str_detect(part1, '_VPRE') ~ 'PRE-ROLL',
                                                         stringr::str_detect(part1, '_VMID') ~ 'MID-ROLL',
                                                         stringr::str_detect(part1, '_VPOS') ~ 'POST-ROLL',
                                                         stringr::str_detect(part1, '_OVRLY') ~ 'VIDEO OVERLAY',
                                                         stringr::str_detect(part1, '_POLV') ~ 'Programmatic Video',
                                                         stringr::str_detect(part1, '_SINS') ~ 'Social In-Stream',
                                                         stringr::str_detect(part1, '_SPRO') ~ 'Social Promotion',
                                                         stringr::str_detect(part1, '_SINF') ~ 'Social In-Feed',
                                                         stringr::str_detect(part1, '_SSTY') ~ 'Social Stories',
                                                         stringr::str_detect(part1, '_SSIF') ~ 'Social Stories & In-Feed',
                                                         stringr::str_detect(part1, '_STKO') ~ 'Social Takeover',
                                                         stringr::str_detect(part1, '_SOCBST') ~ 'Social Boost',
                                                         stringr::str_detect(part1, '_SPOM') ~ 'Placement Optimization \\(multiple\\)',
                                                         stringr::str_detect(part1, '_SNAD') ~ 'Snapchat Snap Ad',
                                                         stringr::str_detect(part1, '_SNCC') ~ 'Snapchat Commercial',
                                                         stringr::str_detect(part1, '_SNLS') ~ 'Snapchat Lens',
                                                         stringr::str_detect(part1, '_SNFT') ~ 'Snapchat Filter',
                                                         stringr::str_detect(part1, '_SNST') ~ 'Snapchat Story',
                                                         stringr::str_detect(part1, '_RPP') ~ 'Reddit Promoted Post',
                                                         stringr::str_detect(part1, '_RAMA') ~ 'Reddit AMA',
                                                         stringr::str_detect(part1, '_RCNV') ~ 'Reddit Conversation',
                                                         stringr::str_detect(part1, '_RTKO') ~ 'Reddit Takeover',
                                                         stringr::str_detect(part1, '_LITA') ~ 'LinkedIn Text Ads',
                                                         stringr::str_detect(part1, '_LISM') ~ 'LinkedIn Sponsored Messaging',
                                                         stringr::str_detect(part1, '_LISC') ~ 'LinkedIn Sponsored Content',
                                                         stringr::str_detect(part1, '_LIDA') ~ 'LinkedIn Dynamic Ad',
                                                         stringr::str_detect(part1, '_TTTV') ~ 'TikTok TopView',
                                                         stringr::str_detect(part1, '_TTBT') ~ 'TikTok Brand Takeover',
                                                         stringr::str_detect(part1, '_TTHC') ~ 'TikTok Hashtag Challenge',
                                                         stringr::str_detect(part1, '_TTBE') ~ 'TikTok Brand Effect',
                                                         stringr::str_detect(part1, '_ABAN') ~ 'Audio BANNER',
                                                         stringr::str_detect(part1, '_ATKO') ~ 'Audio TAKEOVER',
                                                         stringr::str_detect(part1, '_APOD') ~ 'Audio Podcast',
                                                         stringr::str_detect(part1, '_AOVRLY') ~ '15+ Audio Only',
                                                         stringr::str_detect(part1, '_AVID') ~ 'Audio Partner Running Video',
                                                         stringr::str_detect(part1, '_EMAIL') ~ 'EMAIL',
                                                         stringr::str_detect(part1, '_FEE') ~ 'Fee',
                                                         stringr::str_detect(part1, '_RES') ~ 'Research',
                                                         TRUE ~ NA),
           p_network_type = dplyr::case_when(stringr::str_detect(part1, '_YSA') ~ 'Youtube Select - Affinity',
                                             stringr::str_detect(part1, '_YST') ~ 'Youtube Select - YouTube TV',
                                             stringr::str_detect(part1, '_YSH') ~ 'Youtube Select - YouTube Shorts',
                                             stringr::str_detect(part1, '_YMH') ~ 'YouTube - Mastheads',
                                             stringr::str_detect(part1, '_YAX') ~ 'Youtube Auction - Open Exchange',
                                             stringr::str_detect(part1, '_YVA') ~ 'Youtube Auction - Video Action',
                                             stringr::str_detect(part1, '_YAP') ~ 'Youtube Auction - PMP',
                                             stringr::str_detect(part1, '_YDK') ~ 'Youtube - Discovery',
                                             stringr::str_detect(part1, '_FTV') ~ 'Amazon Fire TV',
                                             stringr::str_detect(part1, '_ZDB') ~ 'Amazon IMDB Preroll',
                                             stringr::str_detect(part1, '_APV') ~ 'Amazon Prime Video',
                                             stringr::str_detect(part1, '_NE') ~ 'Network',
                                             stringr::str_detect(part1, '_OO') ~ 'Owned & Operated',
                                             stringr::str_detect(part1, '_POEX') ~ 'Programmatic Open Exchange',
                                             stringr::str_detect(part1, '_PPGD') ~ 'Programmatic PG',
                                             stringr::str_detect(part1, '_PPMPD') ~ 'Programmatic PMP',
                                             stringr::str_detect(part1, '_SSPDID') ~ 'SSP Deal ID',
                                             stringr::str_detect(part1, '_SPMG') ~ 'Social Managed',
                                             stringr::str_detect(part1, '_SPMD') ~ 'Social PMD',
                                             stringr::str_detect(part1, '_SPDR') ~ 'Social Direct',
                                             TRUE ~ NA),
           p_placement_payment_method = dplyr::case_when(stringr::str_detect(part1, '_CPM') ~ 'CPM',
                                                         stringr::str_detect(part1, '_CPC') ~ 'CPC',
                                                         stringr::str_detect(part1, '_DCPM') ~ 'DCPM',
                                                         stringr::str_detect(part1, '_DCPC') ~ 'DCPC',
                                                         stringr::str_detect(part1, '_CPA') ~ 'CPA',
                                                         stringr::str_detect(part1, '_FLAT') ~ 'Fixed Cost',
                                                         stringr::str_detect(part1, '_ADV') ~ 'Added Value',
                                                         stringr::str_detect(part1, '_CPE') ~ 'CPE',
                                                         stringr::str_detect(part1, '_CPV') ~ 'CPV',
                                                         stringr::str_detect(part1, '_CPVH') ~ 'CPVH',
                                                         stringr::str_detect(part1, '_VCPM') ~ 'VCPM',
                                                         stringr::str_detect(part1, '_CPL') ~ 'CPL',
                                                         stringr::str_detect(part1, '_CPUV') ~ 'CPUV',
                                                         stringr::str_detect(part1, '_IDCPM') ~ 'In-Demo CPM',
                                                         stringr::str_detect(part1, '_CPCV') ~ 'CPCV',
                                                         TRUE ~ NA),
           p_serving_method = dplyr::case_when(stringr::str_detect(part1, '_FTDCO') ~ 'Flashtalking DCO',
                                               stringr::str_detect(part1, '_FTOLV') ~ 'Flashtalking OLV',
                                               stringr::str_detect(part1, '_DCMCS') ~ 'CM360 Creative Served',
                                               stringr::str_detect(part1, '_DCMSOCIAL') ~ 'CM360 Social',
                                               stringr::str_detect(part1, '_DCMOBO') ~ 'CM360 1x1',
                                               stringr::str_detect(part1, '_FEEPKG') ~ 'Fee Or Package',
                                               TRUE ~ NA),
           p_video_inventory_type = dplyr::case_when(stringr::str_detect(part1, '_SKCL') ~ 'Skippable and Clickable',
                                                     stringr::str_detect(part1, '_SKNC') ~ 'Skippable and Non-Clickable',
                                                     stringr::str_detect(part1, '_NSCL') ~ 'Non-Skippable and Clickable',
                                                     stringr::str_detect(part1, '_NSNC') ~ 'Non-Skippable and Non-Clickable',
                                                     stringr::str_detect(part1, '_NOVID') ~ 'Not a Video Unit',
                                                     stringr::str_detect(part1, '_SOCVID') ~ 'Social Video',
                                                     stringr::str_detect(part1, '_PRGVD') ~ 'Programmatic Video',
                                                     TRUE ~ NA),
           p_customer_type_audience = dplyr::case_when(stringr::str_detect(part1, '_TOT') ~ 'All',
                                                       stringr::str_detect(part1, '_SUB') ~ 'Sub',
                                                       stringr::str_detect(part1, '_NON') ~ 'Non-Sub',
                                                       TRUE ~ NA),
           p_research_study = dplyr::case_when(stringr::str_detect(part1, '_NORES') ~ 'None',
                                               stringr::str_detect(part1, '_CP') ~ 'Compete',
                                               stringr::str_detect(part1, '_SMBA') ~ 'Samba',
                                               stringr::str_detect(part1, '_KNTR') ~ 'Kantar',
                                               stringr::str_detect(part1, '_DYN') ~ 'Dynata',
                                               stringr::str_detect(part1, '_CS') ~ 'comScore',
                                               stringr::str_detect(part1, '_TAR') ~ 'TAR Research Study',
                                               stringr::str_detect(part1, '_VZ') ~ 'Vizu',
                                               stringr::str_detect(part1, '_PZ') ~ 'Placed',
                                               stringr::str_detect(part1, '_AP') ~ 'Aperture/Pulsepoint',
                                               stringr::str_detect(part1, '_MULT') ~ 'Multiple',
                                               stringr::str_detect(part1, '_VAMP') ~ 'Video Amp',
                                               TRUE ~ NA),
           p_placement_execution_size = dplyr::case_when(stringr::str_detect(part1, '_300x250') ~ '300x250 Placement Size',
                                                         stringr::str_detect(part1, '_240x400') ~ '240x400 Placement Size',
                                                         stringr::str_detect(part1, '_336x280') ~ '336x280 Placement Size',
                                                         stringr::str_detect(part1, '_120x20') ~ '120x20 Placement Size',
                                                         stringr::str_detect(part1, '_300x100') ~ '300x100 Placement Size',
                                                         stringr::str_detect(part1, '_120x600') ~ '120x600 Placement Size',
                                                         stringr::str_detect(part1, '_160x600') ~ '160x600 Placement Size',
                                                         stringr::str_detect(part1, '_300x600') ~ '300x600 Placement Size',
                                                         stringr::str_detect(part1, '_180x150') ~ '180x150 Placement Size',
                                                         stringr::str_detect(part1, '_728x90') ~ '728x90 Placement Size',
                                                         stringr::str_detect(part1, '_468x60') ~ '468x60 Placement Size',
                                                         stringr::str_detect(part1, '_234x60') ~ '234x60 Placement Size',
                                                         stringr::str_detect(part1, '_120x240') ~ '120x240 Placement Size',
                                                         stringr::str_detect(part1, '_125x125') ~ '125x125 Placement Size',
                                                         stringr::str_detect(part1, '_120x90') ~ '120x90 Placement Size',
                                                         stringr::str_detect(part1, '_120x600') ~ '120x60 Placement Size',
                                                         stringr::str_detect(part1, '_88x31') ~ '88x31 Placement Size',
                                                         stringr::str_detect(part1, '_120x30') ~ '120x30 Placement Size',
                                                         stringr::str_detect(part1, '_120x20') ~ '120x20 Placement Size',
                                                         stringr::str_detect(part1, '_168x142') ~ '168x142 Placement Size',
                                                         stringr::str_detect(part1, '_168x28') ~ '168x28 Placement Size',
                                                         stringr::str_detect(part1, '_216x54') ~ '216x54 Placement Size',
                                                         stringr::str_detect(part1, '_216x36') ~ '216xx36 Placement Size',
                                                         stringr::str_detect(part1, '_300x50') ~ '300x50 Placement Size',
                                                         stringr::str_detect(part1, '_320x75') ~ '320x75 Placement Size',
                                                         stringr::str_detect(part1, '_320x50') ~ '320x50 Placement Size',
                                                         stringr::str_detect(part1, '_988x50') ~ '988x50 Placement Size',
                                                         stringr::str_detect(part1, '_500x500') ~ '500x500 Placement Size',
                                                         stringr::str_detect(part1, '_300x300') ~ '300x300 Placement Size',
                                                         stringr::str_detect(part1, '_300x60') ~ '300x60 Placement Size',
                                                         stringr::str_detect(part1, '_1280x100') ~ '1280x100 Placement Size',
                                                         stringr::str_detect(part1, '_480x60') ~ '480x60 Placement Size',
                                                         stringr::str_detect(part1, '_970x66') ~ '970x66 Placement Size',
                                                         stringr::str_detect(part1, '_970x250') ~ '970x250 Placement Size',
                                                         stringr::str_detect(part1, '_1x1') ~ '1x1 Placement Size',
                                                         stringr::str_detect(part1, '_PKG') ~ 'Package',
                                                         stringr::str_detect(part1, '_CSTM') ~ 'Custom',
                                                         stringr::str_detect(part1, '_VID6') ~ 'Video 6 Second',
                                                         stringr::str_detect(part1, '_Vid10') ~ 'Video 10 Second',
                                                         stringr::str_detect(part1, '_VID15') ~ 'Video 15 seconds',
                                                         stringr::str_detect(part1, '_VID30') ~ 'Video 30 seconds',
                                                         stringr::str_detect(part1, '_VID15-30') ~ 'Video 15/30 Seconds',
                                                         stringr::str_detect(part1, '_VID60') ~ 'Video 60 Seconds',
                                                         stringr::str_detect(part1, '_VIDLF') ~ 'Video Long Form',
                                                         stringr::str_detect(part1, '_LOGO') ~ 'Logo',
                                                         stringr::str_detect(part1, '_AUD15') ~ 'Audio 15 seconds',
                                                         stringr::str_detect(part1, '_AUD30') ~ 'Audio 30 seconds',
                                                         stringr::str_detect(part1, '_AUD15-30') ~ 'Audio 15/30 Seconds',
                                                         stringr::str_detect(part1, '_AUD60') ~ 'Audio 60 Seconds',
                                                         stringr::str_detect(part1, '_9x16') ~ '9x16 Placement Size',
                                                         stringr::str_detect(part1, '_16x9') ~ '16x9 Placement Size',
                                                         stringr::str_detect(part1, '_SQAR') ~ 'Square \\(Dynamic Size 100x100, 250x250,etc\\)',
                                                         stringr::str_detect(part1, '_CRSL') ~ 'Carousel',
                                                         stringr::str_detect(part1, '_MOB') ~ 'Mobile',
                                                         TRUE ~ NA),
           p_data_onboarder = dplyr::case_when(stringr::str_detect(part1, '_AAM') ~ 'AAM',
                                               stringr::str_detect(part1, '_LVRMP') ~ 'LiveRamp',
                                               stringr::str_detect(part1, '_EPC') ~ 'Epsilon People Cloud',
                                               stringr::str_detect(part1, '_AEP') ~ 'AEP',
                                               stringr::str_detect(part1, '_NSTR') ~ 'Neustar Transunion',
                                               stringr::str_detect(part1, '_FRTG') ~ 'Floodlight RTG',
                                               stringr::str_detect(part1, '_GARTG') ~ 'Google Analytics RTG',
                                               stringr::str_detect(part1, '_NDBR') ~ 'No Onboarder - No Data Pass',
                                               TRUE ~ NA),
           p_tactic = dplyr::case_when(stringr::str_detect(part1, '_AFAM') ~ 'African American Contextual',
                                       stringr::str_detect(part1, '_AGE18PLUS') ~ 'Age18+',
                                       stringr::str_detect(part1, '_AGE1854') ~ 'Age18-54',
                                       stringr::str_detect(part1, '_AGE21PLUS') ~ 'Age21+',
                                       stringr::str_detect(part1, '_AGE2534') ~ 'Age25-34',
                                       stringr::str_detect(part1, '_AGE2554') ~ 'Age25-54',
                                       stringr::str_detect(part1, '_AGE3554') ~ 'Age35-54',
                                       stringr::str_detect(part1, '_ATTCOMP') ~ 'AT&T Competitive',
                                       stringr::str_detect(part1, '_BTSS') ~ 'Back to School Shoppers',
                                       stringr::str_detect(part1, '_BICULTURAL') ~ 'Bicultural',
                                       stringr::str_detect(part1, '_BDM') ~ 'Business Decision Makers',
                                       stringr::str_detect(part1, '_BOWN') ~ 'Business Owners',
                                       stringr::str_detect(part1, '_BUYFLOW') ~ 'Buyflow',
                                       stringr::str_detect(part1, '_45STAR') ~ 'BYOP',
                                       stringr::str_detect(part1, '_CARRIERS') ~ 'Carriers',
                                       stringr::str_detect(part1, '_CBMOBILE') ~ 'CB Mobile',
                                       stringr::str_detect(part1, '_CHRNL') ~ 'Churn Likely',
                                       stringr::str_detect(part1, '_COLFOOT') ~ 'College Football',
                                       stringr::str_detect(part1, '_CBSUB') ~ 'Comcast Business Customer',
                                       stringr::str_detect(part1, '_CRESISUB') ~ 'Comcast Subscribers',
                                       stringr::str_detect(part1, '_COMPETITIVE') ~ 'Competitive',
                                       stringr::str_detect(part1, '_CCATT') ~ 'Competitive Carrier ATT',
                                       stringr::str_detect(part1, '_CCTMOBILE') ~ 'Competitive Carrier TMobile',
                                       stringr::str_detect(part1, '_CCVRERIZON') ~ 'Competitive Carrier Verizon',
                                       stringr::str_detect(part1, '_CCVRZNATT') ~ 'Competitive Carrier Verizon ATT',
                                       stringr::str_detect(part1, '_CORDCUTTERS') ~ 'Cord Cutters',
                                       stringr::str_detect(part1, '_CORDSHAVERS') ~ 'Cord Shavers',
                                       stringr::str_detect(part1, '_CORDSTACKERS') ~ 'Cord Stackers',
                                       stringr::str_detect(part1, '_DATACENTRIC') ~ 'Data Centric/ Extreme HSD LAL',
                                       stringr::str_detect(part1, '_DCHRN') ~ 'Data Churn',
                                       stringr::str_detect(part1, '_DISCSHOP') ~ 'Discount Shopper',
                                       stringr::str_detect(part1, '_DISCSTORE') ~ 'Discount Store Shopper',
                                       stringr::str_detect(part1, '_DIYER') ~ 'DIYers',
                                       stringr::str_detect(part1, '_DOUBLEPLAY') ~ 'DoublePlay',
                                       stringr::str_detect(part1, '_ENTREP') ~ 'Entrepreneurs',
                                       stringr::str_detect(part1, '_FIWI') ~ 'Fixed Wireless',
                                       stringr::str_detect(part1, '_FWMBS') ~ 'Fixed Wireless & Mobile Substitutor',
                                       stringr::str_detect(part1, '_FLEXLIKELY') ~ 'FLEX 90 Day Activation',
                                       stringr::str_detect(part1, '_FLEXSUBSACTIVE') ~ 'Flex Activation Target',
                                       stringr::str_detect(part1, '_FLEXRECENT') ~ 'Flex Recent Target',
                                       stringr::str_detect(part1, '_FLEXSUBS') ~ 'Flex Subs',
                                       stringr::str_detect(part1, '_FLEXSUBSNOACT') ~ 'Flex Subs No Activation',
                                       stringr::str_detect(part1, '_FTBL') ~ 'Football',
                                       stringr::str_detect(part1, '_GAMERS') ~ 'Gamers',
                                       stringr::str_detect(part1, '_GROWSMB') ~ 'Growing Small Businesses',
                                       stringr::str_detect(part1, '_HISPCHURLAL') ~ 'Hipanic Churn Likely',
                                       stringr::str_detect(part1, '_HISPANIC') ~ 'Hispanic Contextual',
                                       stringr::str_detect(part1, '_HISPFWMBS') ~ 'Hispanic FWA & Mobile Subsitutors',
                                       stringr::str_detect(part1, '_HISPINCCO') ~ 'Hispanic Income Constrained',
                                       stringr::str_detect(part1, '_HISPANICLIKELY') ~ 'Hispanic Likely',
                                       stringr::str_detect(part1, '_HISPMOBLIKELY') ~ 'Hispanic Mobile Likely',
                                       stringr::str_detect(part1, '_HISPMOSUBS') ~ 'Hispanic Mobile Substitors',
                                       stringr::str_detect(part1, '_HISPMOVERS') ~ 'Hispanic Movers',
                                       stringr::str_detect(part1, '_NOWHISPFIWI') ~ 'Hispanic NOW Fixed Wireless',
                                       stringr::str_detect(part1, '_NOWHISPFWMBS') ~ 'Hispanic NOW Fixed Wireless & Mobile Substitutor',
                                       stringr::str_detect(part1, '_NOWHISPMOBSUBS') ~ 'Hispanic NOW Mobile Substitutor',
                                       stringr::str_detect(part1, '_NOWHISPVALUE') ~ 'Hispanic NOW Value',
                                       stringr::str_detect(part1, '_HISPPREMIUM') ~ 'Hispanic Premium',
                                       stringr::str_detect(part1, '_HISPPRMVALUE') ~ 'Hispanic Premium - Value',
                                       stringr::str_detect(part1, '_HISPVALUE') ~ 'Hispanic Value',
                                       stringr::str_detect(part1, '_HISPANICVIDEOLIKELY') ~ 'Hispanic Video Teir Likely',
                                       stringr::str_detect(part1, '_HOMEBUY') ~ 'Homebuyers',
                                       stringr::str_detect(part1, '_HOMEPAGE') ~ 'Homepage',
                                       stringr::str_detect(part1, '_HSD') ~ 'HSD',
                                       stringr::str_detect(part1, '_FLEX') ~ 'HSD Flex Tactic',
                                       stringr::str_detect(part1, '_HSDL') ~ 'HSD Likely',
                                       stringr::str_detect(part1, '_HSDONLY') ~ 'HSD Only',
                                       stringr::str_detect(part1, '_HYPERCONNECTED') ~ 'Hyper Connected',
                                       stringr::str_detect(part1, '_INTERNETESSENTIALS6M') ~ 'IE Recent Tenure',
                                       stringr::str_detect(part1, '_INCCON') ~ 'Income Constrained',
                                       stringr::str_detect(part1, '_IMELECT') ~ 'In-Market Electronics',
                                       stringr::str_detect(part1, '_INTERNETESSENTIALSLAL') ~ 'Internet Essentials LAL',
                                       stringr::str_detect(part1, '_IOSS') ~ 'IOS',
                                       stringr::str_detect(part1, '_IOSATT') ~ 'IOS + ATT Carrier',
                                       stringr::str_detect(part1, '_IOSVRZN') ~ 'IOS + Verizon Carrier',
                                       stringr::str_detect(part1, '_JOBSEEK') ~ 'Job Seekers',
                                       stringr::str_detect(part1, '_LEARNLANDINGLOCAL') ~ 'LearnLandingLocal',
                                       stringr::str_detect(part1, '_LEASEGATEWAY') ~ 'Lease Gateway',
                                       stringr::str_detect(part1, '_LGBTQ') ~ 'LGBTQ',
                                       stringr::str_detect(part1, '_LOCALSEARCHPAGES') ~ 'LocalSearchPages',
                                       stringr::str_detect(part1, '_LONGTERMFORMERS') ~ 'Long Term Formers',
                                       stringr::str_detect(part1, '_LOWHSD') ~ 'Low HSD Tier',
                                       stringr::str_detect(part1, '_MKTEXP') ~ 'Market Expansion',
                                       stringr::str_detect(part1, '_MEDI') ~ 'Medicade',
                                       stringr::str_detect(part1, '_MILITARYLIKELY') ~ 'Military Likely',
                                       stringr::str_detect(part1, '_MOBLIKELY') ~ 'Mobile Likely',
                                       stringr::str_detect(part1, '_MOBONLY') ~ 'Mobile Only',
                                       stringr::str_detect(part1, '_MOPRO') ~ 'Mobile Prospects',
                                       stringr::str_detect(part1, '_MOSUBS') ~ 'Mobile Subsitutor',
                                       stringr::str_detect(part1, '_MOSWITCH') ~ 'Mobile Switchers',
                                       stringr::str_detect(part1, '_MOVERS') ~ 'Movers',
                                       stringr::str_detect(part1, '_MOVERSPMOO') ~ 'Movers - PMOO',
                                       stringr::str_detect(part1, '_MOVERSPMRO') ~ 'Movers - PMRO',
                                       stringr::str_detect(part1, '_MOVERSLIKELY') ~ 'Movers Likely',
                                       stringr::str_detect(part1, '_MOVERSLIKELYEXP') ~ 'Movers Likely Expanded',
                                       stringr::str_detect(part1, '_MOVERSOOF') ~ 'Movers Out of Footprint',
                                       stringr::str_detect(part1, '_MYACCOUNT') ~ 'My Account',
                                       stringr::str_detect(part1, '_MYACCTAPP') ~ 'My Account APP',
                                       stringr::str_detect(part1, '_NASCAR') ~ 'NASCAR',
                                       stringr::str_detect(part1, '_NASCARAUTO') ~ 'NASCAR Auto',
                                       stringr::str_detect(part1, '_NASCARPMP') ~ 'NASCAR PMP',
                                       stringr::str_detect(part1, '_NASCARSPORT') ~ 'NASCAR Sports Fans',
                                       stringr::str_detect(part1, '_NBF') ~ 'New Business Formation',
                                       stringr::str_detect(part1, '_NOWFIWI') ~ 'NOW Fixed Wireless',
                                       stringr::str_detect(part1, '_NOWFWAMBS') ~ 'NOW Fixed Wireless & Mobile Substitutor',
                                       stringr::str_detect(part1, '_NOWMOSUBS') ~ 'NOW Mobile Subsitutor',
                                       stringr::str_detect(part1, '_NOWVALUE') ~ 'NOW Value',
                                       stringr::str_detect(part1, '_NOWHOMEPAGE') ~ 'Now Home Page',
                                       stringr::str_detect(part1, '_NOWINTPP') ~ 'Now Internet Product Page',
                                       stringr::str_detect(part1, '_NOWMOBPP') ~ 'Now Mobile Product Page',
                                       stringr::str_detect(part1, '_NOWMOBSP') ~ 'Now Mobile Shop Page',
                                       stringr::str_detect(part1, '_NOWMOBCUST') ~ 'Now Mobile Customize Page',
                                       stringr::str_detect(part1, '_NOWCTOUTXFI') ~ 'Now Click Out To Xfinity',
                                       stringr::str_detect(part1, '_NOWBFLW') ~ 'Now Buyflow',
                                       stringr::str_detect(part1, '_OFFLINELEADS') ~ 'Offline Leads',
                                       stringr::str_detect(part1, '_OTTLIKELY') ~ 'OTT Likely',
                                       stringr::str_detect(part1, '_PASTVISIT') ~ 'Past Visit',
                                       stringr::str_detect(part1, '_PREMIUM') ~ 'Premium',
                                       stringr::str_detect(part1, '_PREMIUMVALUE') ~ 'Premium-Value',
                                       stringr::str_detect(part1, '_PREMIUMPLUS') ~ 'Premium Plus',
                                       stringr::str_detect(part1, '_PREMIUMWB') ~ 'Premium-Winback',
                                       stringr::str_detect(part1, '_PPLIKELY') ~ 'Prepaid Likley',
                                       stringr::str_detect(part1, '_PPUSER') ~ 'Prepaid User',
                                       stringr::str_detect(part1, '_PRODCUTPAGE') ~ 'ProductPage',
                                       stringr::str_detect(part1, '_QUADPLAY') ~ 'Quad Play',
                                       stringr::str_detect(part1, '_RECENTMOVE') ~ 'Recently Moved',
                                       stringr::str_detect(part1, '_REMOTEWORK') ~ 'Remote Workers',
                                       stringr::str_detect(part1, '_RENTERS') ~ 'Renters',
                                       stringr::str_detect(part1, '_RETAILLIKELY') ~ 'Retail Likely',
                                       stringr::str_detect(part1, '_RETENTION') ~ 'Retention',
                                       stringr::str_detect(part1, '_RONECMASTER') ~ 'RON Catch-All (EC Master)',
                                       stringr::str_detect(part1, '_RON') ~ 'Run of Netowrk',
                                       stringr::str_detect(part1, '_SFU') ~ 'Single-Family Home/Unit',
                                       stringr::str_detect(part1, '_SKEPTICALCUTTERS') ~ 'Skeptical Cutters',
                                       stringr::str_detect(part1, '_SMB') ~ 'SMB BAU',
                                       stringr::str_detect(part1, '_SMBLEAD') ~ 'SMB Leaders',
                                       stringr::str_detect(part1, '_SMBLOAN') ~ 'SMB Loans',
                                       stringr::str_detect(part1, '_HEAVYSOCIAL') ~ 'Social Media Users, Heavy',
                                       stringr::str_detect(part1, '_SPANLG') ~ 'Spanish Language',
                                       stringr::str_detect(part1, '_SPCTRM') ~ 'Spectrum',
                                       stringr::str_detect(part1, '_SPORTS') ~ 'Sports',
                                       stringr::str_detect(part1, '_STREAMAPP') ~ 'Stream App',
                                       stringr::str_detect(part1, '_STREAMPROPENSITY') ~ 'Stream Propensity',
                                       stringr::str_detect(part1, '_STREAMERS') ~ 'Streamers',
                                       stringr::str_detect(part1, '_STUDENTLIKELY') ~ 'Student Likely',
                                       stringr::str_detect(part1, '_FLEXENGAGEMENT') ~ 'Sub Flex Target',
                                       stringr::str_detect(part1, '_VIDEOFORMERSA1224') ~ 'Sub Video Formers A 12-24',
                                       stringr::str_detect(part1, '_VIDEOFORMERSA6') ~ 'Sub Video Formers A 6',
                                       stringr::str_detect(part1, '_VIDEOFORMERSA612') ~ 'Sub Video Formers A 6-12',
                                       stringr::str_detect(part1, '_TECHIES') ~ 'Technies',
                                       stringr::str_detect(part1, '_TELEMUNDOSS') ~ 'Telemundo \\(Spanish Speaking\\)',
                                       stringr::str_detect(part1, '_TRIPLEPLAYLIKELY') ~ 'Triple Play Likely',
                                       stringr::str_detect(part1, '_TRIPLEPLAY') ~ 'TriplePlay',
                                       stringr::str_detect(part1, '_TVTRADITIONALS') ~ 'TV Traditionals',
                                       stringr::str_detect(part1, '_HTVVIEW') ~ 'TV Viewership, Heavy',
                                       stringr::str_detect(part1, '_LTVVIEW') ~ 'TV Viewership, Light',
                                       stringr::str_detect(part1, '_MTVVIEW') ~ 'TV Viewership, Medium',
                                       stringr::str_detect(part1, '_UNDERFIFTYEMP') ~ 'Under 50 Employees',
                                       stringr::str_detect(part1, '_UNIVERSITY') ~ 'University',
                                       stringr::str_detect(part1, '_VALUE') ~ 'Value',
                                       stringr::str_detect(part1, '_VERIZONCOMP') ~ 'Verizon Competitive',
                                       stringr::str_detect(part1, '_VSB') ~ 'Very Small Business',
                                       stringr::str_detect(part1, '_VET') ~ 'Veterans',
                                       stringr::str_detect(part1, '_VIDEOCUSTOMER') ~ 'Video Customers',
                                       stringr::str_detect(part1, '_VIDEODOWNGRADELIKELY') ~ 'Video Downgrade Likely',
                                       stringr::str_detect(part1, '_VIDEOLIKELY') ~ 'Video Likely',
                                       stringr::str_detect(part1, '_X1') ~ 'X1',
                                       stringr::str_detect(part1, '_XMSUBS') ~ 'Xfinity Mobile Subs',
                                       stringr::str_detect(part1, '_XFINITYSTREAM') ~ 'Xfinity Stream',
                                       stringr::str_detect(part1, '_XHSUBS') ~ 'XH AAM Subs',
                                       stringr::str_detect(part1, '_XHLIKELY') ~ 'XH Likely',
                                       stringr::str_detect(part1, '_CBXMAPPROVED') ~ 'XM CB Approved',
                                       stringr::str_detect(part1, '_XML') ~ 'XM Likely',
                                       TRUE ~ NA),
           p_data_source_targeting_type = dplyr::case_when(stringr::str_detect(part1, '_1P') ~ 'First Party',
                                                           stringr::str_detect(part1, '_2P') ~ 'Second Party',
                                                           stringr::str_detect(part1, '_CNTEXT') ~ 'Contextual Segment',
                                                           stringr::str_detect(part1, '_LAL2') ~ '2P - Look a like',
                                                           stringr::str_detect(part1, '_LAL3') ~ '3P - Look a Like',
                                                           stringr::str_detect(part1, '_ISPDATA') ~ 'ISP- data source',
                                                           stringr::str_detect(part1, '_RTG2') ~ 'RTG',
                                                           stringr::str_detect(part1, '_NODT') ~ 'No Data Targeting',
                                                           stringr::str_detect(part1, '_3P') ~ 'Third Party',
                                                           TRUE ~ NA),
           p_targeting_kpi = dplyr::case_when(stringr::str_detect(part1, '_CPAXM') ~ 'CPA - Cost Per XM order',
                                              stringr::str_detect(part1, '_CPAIE') ~ 'CPA - Cost Per IE order',
                                              stringr::str_detect(part1, '_CPAPP') ~ 'CPA- Cost Per Pre-Paid Order',
                                              stringr::str_detect(part1, '_RCH') ~ 'Reach',
                                              stringr::str_detect(part1, '_CPLB') ~ 'CPL - Cost Per business lead',
                                              stringr::str_detect(part1, '_CPVH') ~ 'CPV - Home Page',
                                              stringr::str_detect(part1, '_SVST') ~ 'CPSVST - Site Visits',
                                              stringr::str_detect(part1, '_CPVSV') ~ 'CPB - Cost Per Shopping Visit',
                                              stringr::str_detect(part1, '_CPVIE') ~ 'CPV - Cost Per IE visit',
                                              stringr::str_detect(part1, '_CPVM') ~ 'CPV - Cost Per mover\'s page',
                                              stringr::str_detect(part1, '_CPVXH') ~ 'CPV - Cost per XH visit',
                                              stringr::str_detect(part1, '_CPAXH') ~ 'CPA - Cost Per XH Order',
                                              stringr::str_detect(part1, '_CPVPP') ~ 'CPV - Cost Per Pre-Paid Visit',
                                              stringr::str_detect(part1, '_CPVXM') ~ 'CPV - Cost per XM Visit',
                                              stringr::str_detect(part1, '_CTRP') ~ 'CTR - Click Through Rate',
                                              stringr::str_detect(part1, '_ACR') ~ 'Audio Completion Rate',
                                              stringr::str_detect(part1, '_CPAR') ~ 'Cost Per Orders',
                                              stringr::str_detect(part1, '_STV') ~ 'Store Visitation',
                                              stringr::str_detect(part1, '_RECH') ~ 'Social - Reach',
                                              stringr::str_detect(part1, '_AWA') ~ 'Social - Awareness',
                                              stringr::str_detect(part1, '_TRAF') ~ 'Social - Traffic',
                                              stringr::str_detect(part1, '_VV') ~ 'Social - Video Views',
                                              stringr::str_detect(part1, '_CAT') ~ 'Social - Catalog',
                                              stringr::str_detect(part1, '_CONV') ~ 'Social - Conversions',
                                              stringr::str_detect(part1, '_LEAD') ~ 'Social - Lead Gen',
                                              stringr::str_detect(part1, '_VCRP') ~ 'VCR - Video Completion Rate',
                                              TRUE ~ NA),
           p_creative_targeting_decision_dco = dplyr::case_when(stringr::str_detect(part1, '_PLID') ~ 'Placement ID Targeted',
                                                                stringr::str_detect(part1, '_DACT') ~ 'Dyanmic Audience Creative targeting \\(FT Passive\\)',
                                                                stringr::str_detect(part1, '_CTPAS') ~ 'Contextual Passive',
                                                                stringr::str_detect(part1, '_TOMO') ~ 'Two or More',
                                                                stringr::str_detect(part1, '_NOCT') ~ 'None',
                                                                TRUE ~ NA),
           p_browser_devices = dplyr::case_when(stringr::str_detect(part1, '_CLBRS') ~ 'Cookie limited browsers \\(Safari, FireFox\\)',
                                                stringr::str_detect(part1, '_CBRWS') ~ 'Cookie browsers \\(Chrome, Edge\\)',
                                                stringr::str_detect(part1, '_NAPP') ~ 'In App',
                                                stringr::str_detect(part1, '_ABAD') ~ 'All browsers/devices',
                                                TRUE ~ NA)
    )
}
